# Generated by Django 4.1.1 on 2022-09-16 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_url', models.URLField()),
                ('third_party_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('third_party_id', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSectionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('third_party_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.coursesection')),
            ],
        ),
    ]
